### PR TITLE
Add additional custom directives to proxied locations

### PR DESCRIPTION
**Pull request by manics**
This further enables custom additions to the configuration by adding an option for adding directives to each server location.

Tag: `1.14.0` new feature

### CODE REVIEW

**Comment by joshmoore** [comment]
Makes sense :+1: Only question is whether the naming matches other roles where we've done the same thing. If so, GFI.

**Comment by manics** [comment]
I think this is the only role that supports this kind of extensibility. Related properties in this role are:
- `nginx_proxy_additional_maps`
- `nginx_proxy_additional_directives`

I went for `.additional` to keep it short, but I can change it to `.additional_directives` if you think that's better?

**Comment by joshmoore** [comment]
Looks like this repo already has quite a mix:
```
# nginx-proxy
nginx_proxy_direct_locations.custom: List of additional configuration directives
nginx_proxy_upstream_servers.additional: List of additional directives
nginx_proxy_conf_http: Additional directives 
nginx_proxy_additional_maps: List of custom Nginx maps 
nginx_proxy_additional_directives: List of additional directives
```
so maybe if you think there would ever be more than the one "additional" in this case, then add `_$suffix`. Otherwise, leave as `additional`.


FYI:

```
# web
omero_web_omego_additional_args

# postgresql
extra_options

# munin
extraclea

# haproxy
extra_opts

# devspace
extra_args

# certbot
extra_parameters
```

**Comment by sbesson** [comment]
Following the latest tag, can the role be imported manually to https://galaxy.ansible.com/ome/nginx_proxy until we sort out the automation release?

**Pull request merged**
